# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Git Blog
email: jm0309@kookmin.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  Here is jm3789's Git Blog!
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jm3789.github.io" # the base hostname & protocol for your site
twitter_username: (-)
github_username:  jm3789

# Build settings
markdown: kramdown

comment:
  provider: "disqus"
  disqus: 
    shortname: jm3789
